backend = "glx";
vsync = true;

@include "opacity.conf"


# Stability
detect-client-opacity = true;
use-damage = false;

corner-radius = 0;

active-opacity = 1.0;
inactive-opacity = 1.0;

opacity-rule = [
  "100:class_g = 'kitty'"
];

unredir-if-possible = false;
