vo=gpu-next
gpu-api=d3d11
hwdec=d3d11va
target-colorspace-hint=yes
hdr-compute-peak=yes
dscale=mitchell
correct-downscaling=yes
linear-downscaling=yes
# shrink video to 1080p-size inside fullscreen, black bars around
video-scale-x=0.75
video-scale-y=0.75
fullscreen=yes
keep-open=yes
tone-mapping=spline
tone-mapping-mode=rgb

# grain / banding smoothing
deband=yes
deband-iterations=2
deband-threshold=35
deband-range=20
video-output-levels=full

target-contrast=inf
target-min=0
