#!/bin/bash
# Regenerate the *.pending.txt lists from explicit packages not yet approved; promote a line into pkglist-*.txt to approve it.
set -eu

DOTFILES="$(cd "$(dirname "$0")/.." && pwd)"
cd "$DOTFILES/install"

read_list() { grep -vE '^[[:space:]]*(#|$)' "$1" 2>/dev/null || true; }

# Expand group tokens (e.g. base-devel) so their members aren't reported as unapproved.
expand_groups() {
  local p m
  while read -r p; do
    [ -z "$p" ] && continue
    m=$(pacman -Sqg "$p" 2>/dev/null || true)
    if [ -n "$m" ]; then echo "$m"; else echo "$p"; fi
  done
  return 0
}

approved_pac=$(read_list pkglist-pacman.txt | expand_groups | sort -u)
approved_aur=$(read_list pkglist-aur.txt | sort -u)
exp_pac=$(pacman -Qqen | sort -u)
exp_aur=$(pacman -Qqem | grep -vxE 'yay|eww' | sort -u)   # yay + eww are built directly in setup.sh, not approved-listed

pending_pac=$(comm -23 <(echo "$exp_pac") <(echo "$approved_pac"))
pending_aur=$(comm -23 <(echo "$exp_aur") <(echo "$approved_aur"))

write() {  # $1=file  $2=header  $3=body
  { echo "$2"; [ -n "$3" ] && echo "$3"; } > "$1"
}
write pkglist-pacman.pending.txt \
  "# Unapproved native packages: installed but not in pkglist-pacman.txt. Move a line there to approve. Regenerated by pkglist-sync.sh." \
  "$pending_pac"
write pkglist-aur.pending.txt \
  "# Unapproved AUR packages: installed but not in pkglist-aur.txt. Move a line there to approve. Regenerated by pkglist-sync.sh." \
  "$pending_aur"

echo "pending native: $(echo "$pending_pac" | grep -c . || true)"
echo "pending AUR:    $(echo "$pending_aur" | grep -c . || true)"
