exec_always --no-startup-id xsetroot -solid "#333333"
exec_always --no-startup-id gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec_always --no-startup-id gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

bar {
    status_command i3status -c ~/.config/i3status/config
    colors {
        background #1e1e1e
        statusline #d4d4d4
        separator  #555555
        focused_workspace  #264f78 #264f78 #ffffff
        active_workspace   #333333 #333333 #d4d4d4
        inactive_workspace #1e1e1e #1e1e1e #888888
        urgent_workspace   #cc0000 #cc0000 #ffffff
    }
}
