include theme.conf

shell /bin/zsh
font_family      JetBrains Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 20.0

# background_opacity is set per-theme in theme-{dark,light}.conf
